<?php

/**
 * Implements hook_theme()
 */
function views_cycle2_theme() {
  return array(
    'views_cycle2' => array(
      'variables' => array('form' => NULL),
    )
  );
}

function template_preprocess_views_cycle2(&$variables) {
  libraries_load('jquery.cycle2');
  drupal_add_js(drupal_get_path('module', 'views_cycle2') . '/views-cycle2.js');
  drupal_add_js(drupal_get_path('module', 'views_cycle2') . '/verticalScroll.js');
  $view = $variables['view'];
  // settings
  $options = $view->style_plugin->options;
  $slide_attributes = array();
  $variables['show_pager'] = $options['show_pager'];

  $included = array('fx', 'speed', 'swipe', 'timeout', 'allow-wrap', 'auto-height');
  $boolean = array('allow-wrap');

  foreach($options as $index => $option) {
    if(in_array($index, $included)) {
      $name = 'data-cycle-' . $index;

      if(in_array($index, $boolean)) {

        if($option) {
          $option = 'true';
        } else {
          $option = 'false';
        }
      }
      $slider_attributes[$name] = $option;
    }
  }


  $variables['pager'] = 'cycle-pager-' . $view->vid;
  $variables['slider_attributes'] = $slider_attributes;

}

/**
 * Implements hook_views_api().
 */
function views_cycle2_views_api() {
  return array(
    'api' => 3.0,
  );
}

function views_cycle2_libraries_info() {
  $libraries['jquery.cycle2'] = array(
    'name' => 'Cycle2',
    'vendor url' => 'http://jquery.malsup.com/cycle2/',
    'download url' => 'http://jquery.malsup.com/cycle2/download/',
    'version arguments' => array(
      'file' => 'jquery.cycle2.js',
      // Version: BETA-20121030
      'pattern' => '/ver.*? ([a-z0-9\-\.]+)/i',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array('jquery.cycle2.js'),
    ),
    'variants' => array(
      'minified' => array(
        'version arguments' => array(
          'file' => 'jquery.cycle2.min.js',
        ),
        'files' => array(
          'js' => array('jquery.cycle2.min.js'),
          // Version: BETA-20121030
          'pattern' => '/ver.*? ([a-z0-9\-\.]+)/i',
          'lines' => 5,
        ),
        'variant arguments' => array(
          'variant' => 'minified',
        ),
        'variant callback' => '_views_cycle2_detect_minified',
      ),
    ),
  );

  return $libraries;
}


function _views_cycle2_detect_minified($library) {
  $library_path = DRUPAL_ROOT . '/' . $library['library path'] . '/';

  return file_exists($library_path . 'jquery.cycle2.min.js');
}